### ISSUE TITLE
Unknown setting 'PREFECT_SERVER_ALLOW_EPHEMERAL_MODE'

### ISSUE THREAD

**Issue by trymzet** [PrefectHQ/actions-prefect-deploy#55]
Hello, I'm trying to use this action with standard settings but can't get this to work.

I do not have any Prefect profiles set up in my workflow - I use Prefect's official auth action to authenticate. Could you please help debugging this?

```yaml
on:
  pull_request:
    branches: [main]
    paths:
      - "prefect.yaml"

  workflow_dispatch:

jobs:
  apply_prefect_deployments:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -q prefect
        
      - name: Prefect Auth
        uses: PrefectHQ/actions-prefect-auth@v2
        with:
          prefect-api-key: ${{ secrets.PREFECT_API_KEY }}
          prefect-workspace: ${{ vars.PREFECT_WORKSPACE }}

      - name: Run Prefect Deploy
        uses: PrefectHQ/actions-prefect-deploy@v3
        with:
          deployment-names: abc
          pyproject-toml-path: pyproject.toml
```

Traceback:
```python
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.7/x64/bin/prefect", line 5, in <module>
    from prefect.cli import app
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/prefect/__init__.py", line 30, in <module>
    from prefect.deployments import deploy
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/prefect/deployments/__init__.py", line 2, in <module>
    import prefect.deployments.steps
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/prefect/deployments/steps/__init__.py", line 2, in <module>
    from .pull import (
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/prefect/deployments/steps/pull.py", line 11, in <module>
    from prefect.runner.storage import BlockStorageAdapter, GitRepository, RemoteStorage
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/prefect/runner/__init__.py", line 1, in <module>
    from .runner import Runner
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/prefect/runner/runner.py", line 73, in <module>
    from prefect.deployments.deployments import load_flow_from_flow_run
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/prefect/deployments/deployments.py", line 51, in <module>
    from prefect.context import FlowRunContext, PrefectObjectRegistry, TaskRunContext
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/prefect/context.py", line 571, in <module>
    GLOBAL_SETTINGS_CONTEXT: SettingsContext = root_settings_context()
                                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/prefect/context.py", line 534, in root_settings_context
    profiles = prefect.settings.load_profiles()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/prefect/settings.py", line 2[337](https://github.com/dyvenia/edp-phoebe-flows/actions/runs/11295033606/job/31416855396#step:7:340), in load_profiles
    user_profiles = _read_profiles_from(user_profiles_path)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/prefect/settings.py", line 2313, in _read_profiles_from
    profiles.append(Profile(name=name, settings=settings, source=path))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/pydantic/v1/main.py", line [341](https://github.com/dyvenia/edp-phoebe-flows/actions/runs/11295033606/job/31416855396#step:7:344), in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for Profile
settings
  Unknown setting 'PREFECT_SERVER_ALLOW_EPHEMERAL_MODE'. (type=value_error)
  ```

**Comment by trymzet** [comment]
NVM - I was using `v3` version of this action, `v4` works as expected.
